### ISSUE TITLE
`document.defaultView._core` is undefined

### ISSUE THREAD

**Issue by clintharris** [wallabyjs/jsdom-quokka-plugin#5] opened 2018-01-23 13:27 UTC
Quokka is awesome! I'm trying to run `quokka-react-sample` and get the following error on Quokka startup, however:

```
​​​​Quokka #1 (node: v8.9.4, babel: v6.26.0)​​​​
​​​​
​​Cannot convert undefined or null to object​​
  at ​​​Object.before​​​ ​./node_modules/jsdom-quokka-plugin/index.js:12​
```
Here's a code snippet from `jsdom-quokka-plugin/index.js` showing the line with the issue:
```javascript
module.exports = {
  before: config => {
    const fs = require('fs');
    const pluginConfig = config.jsdom || {};
    const jsdomConfig = pluginConfig.config || {};
    const fileData = jsdomConfig.file && fs.readFileSync(jsdomConfig.file).toString();
    const html = fileData || pluginConfig.html || '<!doctype html><html><head><meta charset="utf-8"></head><body><div id="root"></div></body></html>';
    const jsdom = require('jsdom/lib/old-api.js');
    const document = jsdom.jsdom(html, jsdomConfig);
    
    Object.getOwnPropertyNames(document.defaultView)
      .concat(Object.getOwnPropertyNames(document.defaultView._core)) //  👈 "._core" is undefined
```

## Steps to reproduce
I have been able to reproduce the issue on two machines with the following steps:

1. Environment:
    - Node 8.9.4
    - Babel 6.26.0
    - VSCode 1.19.2
    - quokka-vscode 1.0.94
    - jsdom-quokka-plugin 1.0.9
    - quokka-react-sample `master:32a2bc0`

2. Clone `quokka-react-sample` and install:
```
git clone git@github.com:wallabyjs/quokka-react-sample.git
cd quokka-react-sample
npm install
```

3. Open `quokka-react-sample/quokka.js` in VSCode and start Quokka.

**Comment by ArtemGovorov** [comment] 2018-01-24 02:08
Thanks for the report. The issue is fixed in the latest jsdom-quokka-plugin v1.0.10. Please update the module to the latest version and it should work.

**Closed by ArtemGovorov** 2018-01-24 02:08 UTC
